import { FIX_LABELS, FIX_TYPES } from '../../config/constants.js';
import { getFileContent } from '../github/repo.js';
import { parseUnifiedDiff, applyDiffToContent } from '../patch/index.js';
import { logger } from '../../api/webhooks/index.js';

export async function createPR(octokit, context, fixType, diff, trustBody) {
  const { owner, repo, defaultBranch, headSha, fileContents } = context;

  const branchName = `autopr/${fixType}/${Date.now()}`;
  const label = FIX_LABELS[fixType] || 'fix: automated patch';

  try {
    await octokit.rest.git.createRef({
      owner, repo,
      ref: `refs/heads/${branchName}`,
      sha: headSha,
    });

    const diffFiles = parseUnifiedDiff(diff);
    const newTree = [];

    for (const df of diffFiles) {
      const filePath = df.oldPath;
      const originalContent = fileContents[filePath];
      if (!originalContent) continue;

      const newContent = applyDiffToContent(originalContent, df);
      if (newContent === originalContent) continue;

      const { data: blob } = await octokit.rest.git.createBlob({
        owner, repo,
        content: newContent,
        encoding: 'utf-8',
      });

      newTree.push({
        path: filePath,
        mode: '100644',
        type: 'blob',
        sha: blob.sha,
      });
    }

    if (newTree.length === 0) {
      throw new Error('No changes to commit');
    }

    const { data: tree } = await octokit.rest.git.createTree({
      owner, repo,
      base_tree: headSha,
      tree: newTree,
    });

    const { data: commit } = await octokit.rest.git.createCommit({
      owner, repo,
      message: label,
      tree: tree.sha,
      parents: [headSha],
    });

    await octokit.rest.git.updateRef({
      owner, repo,
      ref: `heads/${branchName}`,
      sha: commit.sha,
    });

    const prBody = trustBody || buildPRBody(fixType, diff);

    const { data: pr } = await octokit.rest.pulls.create({
      owner, repo,
      title: label,
      head: branchName,
      base: defaultBranch,
      body: prBody,
    });

    logger.info({ prNumber: pr.number, prUrl: pr.html_url, fixType }, 'PR created');
    return { ...pr, trustScore: context._trustScore };
  } catch (err) {
    logger.error({ err, fixType }, 'Failed to create PR');
    throw err;
  }
}

function buildPRBody(fixType, diff) {
  const summary = {
    [FIX_TYPES.DEPENDENCY]: 'Updates an outdated dependency to a compatible version.',
    [FIX_TYPES.LINT]: 'Fixes lint/formatting issues to comply with project style rules.',
    [FIX_TYPES.CI_FAILURE]: 'Fixes a CI configuration issue that was causing a build failure.',
    [FIX_TYPES.TRIVIAL_BUG]: 'Fixes a trivial bug identified in the codebase.',
  };

  return `## 🤖 AutoPR — ${summary[fixType] || 'Automated fix'}

\`\`\`diff
${diff.slice(0, 2000)}
\`\`\`

<sub>Generated by AutoPR. This is an automated pull request. Please review carefully before merging.</sub>

---
🚀 **Love automated fixes?** [Upgrade to AutoPR Pro](https://autopr.dev/upgrade) — unlimited PRs, priority processing, and advanced fix patterns for \$19/month.
`;
}
